



POST http://127.0.0.1:8000/api/ojttrainies/
Content-Type: application/json

{
    "province": "Hell",
    "school_name": "BSU",
    "ojt_duration": 500,
    "school_address": "Alangilan",
    "contact_person": "Jaja Mendoza",
    "contact_number": "1234567890",
    "student_name": "Mary Mendoza",
    "sex": "Female",
    "start_date": "2024-02-05",
    "end_date": "2024-08-05",
    "mode": "Work From Home",
    "recommendation_letter": true,
    "application_form": true,
    "cv_resume": true,
    "medical_certificate": true,
    "workplan_form": true,
    "interview_form": true,
    "acceptance_letter": true,
    "wfh_arrangement": true,
    "nda": true,
    "work_assignment_form": true,
    "war": true,
    "timesheet": true,
    "coc": true,
    "remarks": "N/A"
}