# Generated by Django 5.0.2 on 2024-02-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='engage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('nameofoffice', models.CharField(max_length=255)),
                ('contactnumber', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'engage',
            },
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojt_duration', models.IntegerField()),
                ('province', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('school_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'InternshipApplication',
            },
        ),
    ]
