# Generated by Django 5.0.2 on 2024-02-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='engage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('nameofoffice', models.CharField(max_length=255)),
                ('contactnumber', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'engage',
            },
        ),
        migrations.CreateModel(
            name='intern_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=200)),
                ('ojt_duration', models.IntegerField()),
                ('school_address', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mode', models.CharField(max_length=20)),
                ('recommendation_letter', models.BooleanField(default=False)),
                ('application_form', models.BooleanField(default=False)),
                ('cv_resume', models.BooleanField(default=False)),
                ('medical_certificate', models.BooleanField(default=False)),
                ('workplan_form', models.BooleanField(default=False)),
                ('interview_form', models.BooleanField(default=False)),
                ('acceptance_letter', models.BooleanField(default=False)),
                ('wfh_arrangement', models.BooleanField(default=False)),
                ('nda', models.BooleanField(default=False)),
                ('work_assignment_form', models.BooleanField(default=False)),
                ('war', models.BooleanField(default=False)),
                ('timesheet', models.BooleanField(default=False)),
                ('coc', models.BooleanField(default=False)),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'intern_table',
            },
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojt_duration', models.IntegerField()),
                ('province', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('school_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'InternshipApplication',
            },
        ),
    ]
