# Generated by Django 5.0.2 on 2024-02-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern_table',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
